import { z } from 'zod';

export const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  PORT: z.coerce.number().int().positive().default(5000),
  DATABASE_URL: z.string().url({ message: 'DATABASE_URL must be a valid URL' }),
  JWT_SECRET: z.string().min(32, { message: 'JWT_SECRET must be at least 32 characters' }),
  MASTER_API_KEY: z.string().min(1, { message: 'MASTER_API_KEY is required' }),
  REDIS_URL: z.string().url({ message: 'REDIS_URL must be a valid URL' }),
  ALLOWED_ORIGINS: z.string().transform((val) => val.split(',').map((s) => s.trim())),
  SENTRY_DSN: z.string().url().optional(),
  LOG_LEVEL: z.enum(['error', 'warn', 'info', 'debug']).optional(),
  FCM_SERVER_KEY: z.string().optional(),
  FCM_SENDER_ID: z.string().optional(),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().optional(),
  SMTP_USER: z.string().optional(),
  SMTP_PASS: z.string().optional(),
  AWS_ACCESS_KEY_ID: z.string().optional(),
  AWS_SECRET_ACCESS_KEY: z.string().optional(),
  AWS_REGION: z.string().optional(),
  AWS_S3_BUCKET: z.string().optional(),
  TWILIO_ACCOUNT_SID: z.string().optional(),
  TWILIO_AUTH_TOKEN: z.string().optional(),
  TWILIO_PHONE_NUMBER: z.string().optional(),
  DISABLE_RATE_LIMIT: z.string().optional().transform((v) => v === 'true'),
}).transform((data) => ({
  nodeEnv: data.NODE_ENV,
  port: data.PORT,
  databaseUrl: data.DATABASE_URL,
  jwtSecret: data.JWT_SECRET,
  masterApiKey: data.MASTER_API_KEY,
  redisUrl: data.REDIS_URL,
  allowedOrigins: data.ALLOWED_ORIGINS,
  sentryDsn: data.SENTRY_DSN,
  logLevel: data.LOG_LEVEL,
  fcmServerKey: data.FCM_SERVER_KEY,
  fcmSenderId: data.FCM_SENDER_ID,
  smtpHost: data.SMTP_HOST,
  smtpPort: data.SMTP_PORT,
  smtpUser: data.SMTP_USER,
  smtpPass: data.SMTP_PASS,
  awsAccessKeyId: data.AWS_ACCESS_KEY_ID,
  awsSecretAccessKey: data.AWS_SECRET_ACCESS_KEY,
  awsRegion: data.AWS_REGION,
  awsS3Bucket: data.AWS_S3_BUCKET,
  twilioAccountSid: data.TWILIO_ACCOUNT_SID,
  twilioAuthToken: data.TWILIO_AUTH_TOKEN,
  twilioPhoneNumber: data.TWILIO_PHONE_NUMBER,
  disableRateLimit: data.DISABLE_RATE_LIMIT,
}));

export type EnvConfig = z.infer<typeof envSchema>;